-- Person 5 core data model for hosted or self-hosted Supabase.
-- Safe to run repeatedly; existing application data is preserved.

create extension if not exists postgis;
create extension if not exists pgcrypto;

-- SQLAlchemy installations may already use a PostgreSQL enum for status.
do $$
begin
  if exists (select 1 from pg_type where typname = 'incident_status_enum') then
    alter type incident_status_enum add value if not exists 'CLOSED';
    alter type incident_status_enum add value if not exists 'REOPENED';
  end if;
end;
$$;

create table if not exists public.areas (
  id bigint generated by default as identity primary key,
  name text not null,
  district_code text not null unique,
  state text not null default 'Tamil Nadu',
  latitude double precision,
  longitude double precision,
  current_state text not null default 'NORMAL'
    check (current_state in ('NORMAL', 'ALERT', 'EMERGENCY', 'RECOVERY')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  phone text not null unique,
  name text,
  role text not null default 'citizen'
    check (role in ('citizen', 'responder', 'cpoc_admin')),
  area_id bigint references public.areas(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incidents (
  id bigint generated by default as identity primary key,
  area_id bigint references public.areas(id) on delete set null,
  reporter_id bigint,
  incident_type text not null,
  severity text not null,
  title text not null,
  description text,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  location geography(point, 4326) not null,
  status text not null default 'OPEN',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  external_event_id text unique,
  source_device_id text,
  duplicate_of_id bigint references public.incidents(id) on delete set null,
  verification_note text,
  verified_by uuid references public.users(id) on delete set null,
  verified_at timestamptz,
  location_flagged boolean not null default false,
  location_flag_reason text,
  closure_photo_distance_meters double precision
);

-- Upgrade databases that already contain the original incidents table.
alter table public.incidents add column if not exists area_id bigint references public.areas(id) on delete set null;
alter table public.incidents add column if not exists verification_note text;
alter table public.incidents add column if not exists verified_by uuid references public.users(id) on delete set null;
alter table public.incidents add column if not exists verified_at timestamptz;
alter table public.incidents add column if not exists location_flagged boolean not null default false;
alter table public.incidents add column if not exists location_flag_reason text;
alter table public.incidents add column if not exists closure_photo_distance_meters double precision;

create table if not exists public.photos (
  id uuid primary key default gen_random_uuid(),
  incident_id bigint references public.incidents(id) on delete cascade,
  object_key text not null unique,
  content_type text not null,
  size_bytes bigint,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  caption text,
  latitude double precision check (latitude between -90 and 90),
  longitude double precision check (longitude between -180 and 180),
  captured_at timestamptz,
  uploaded_by uuid references public.users(id) on delete set null,
  uploaded_at timestamptz not null default now(),
  verified_at timestamptz,
  verified_by uuid references public.users(id) on delete set null
);

create index if not exists idx_incidents_area_status on public.incidents(area_id, status);
create index if not exists idx_incidents_location_gist on public.incidents using gist(location);
create index if not exists idx_incidents_type_created on public.incidents(incident_type, created_at desc);
create index if not exists idx_photos_incident on public.photos(incident_id);

create or replace function public.approve_incident(
  p_incident_id bigint, p_verified_by uuid, p_note text default null
) returns public.incidents
language plpgsql security definer set search_path = public as $$
declare result public.incidents;
begin
  update public.incidents
  set status = 'CLOSED', verification_note = p_note,
      verified_by = p_verified_by, verified_at = now(), updated_at = now()
  where id = p_incident_id returning * into result;
  if result.id is null then raise exception 'Incident % not found', p_incident_id; end if;
  return result;
end;
$$;

create or replace function public.reject_incident(
  p_incident_id bigint, p_verified_by uuid, p_reason text
) returns public.incidents
language plpgsql security definer set search_path = public as $$
declare result public.incidents;
begin
  if coalesce(trim(p_reason), '') = '' then raise exception 'Rejection reason is required'; end if;
  update public.incidents
  set status = 'REOPENED', verification_note = p_reason,
      verified_by = p_verified_by, verified_at = now(), updated_at = now()
  where id = p_incident_id returning * into result;
  if result.id is null then raise exception 'Incident % not found', p_incident_id; end if;
  return result;
end;
$$;

-- Publish Person 5 tables through Supabase Realtime when the publication exists.
do $$
declare table_name text;
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    foreach table_name in array array['areas', 'users', 'incidents', 'photos'] loop
      if not exists (
        select 1 from pg_publication_tables
        where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = table_name
      ) then
        execute format('alter publication supabase_realtime add table public.%I', table_name);
      end if;
    end loop;
  end if;
end;
$$;
